<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: inbox.proto

namespace Inbox;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>inbox.AddInboxData</code>
 */
class AddInboxData extends \Google\Protobuf\Internal\Message
{
    /**
     *邮件模板id
     *
     * Generated from protobuf field <code>int64 inbox_id = 1;</code>
     */
    protected $inbox_id = 0;
    /**
     *邮件生效时间
     *
     * Generated from protobuf field <code>string start_time = 2;</code>
     */
    protected $start_time = '';
    /**
     *邮件失效时间
     *
     * Generated from protobuf field <code>string end_time = 3;</code>
     */
    protected $end_time = '';
    /**
     *邮件所需参数json
     *
     * Generated from protobuf field <code>string params = 4;</code>
     */
    protected $params = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int|string $inbox_id
     *          邮件模板id
     *     @type string $start_time
     *          邮件生效时间
     *     @type string $end_time
     *          邮件失效时间
     *     @type string $params
     *          邮件所需参数json
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Inbox::initOnce();
        parent::__construct($data);
    }

    /**
     *邮件模板id
     *
     * Generated from protobuf field <code>int64 inbox_id = 1;</code>
     * @return int|string
     */
    public function getInboxId()
    {
        return $this->inbox_id;
    }

    /**
     *邮件模板id
     *
     * Generated from protobuf field <code>int64 inbox_id = 1;</code>
     * @param int|string $var
     * @return $this
     */
    public function setInboxId($var)
    {
        GPBUtil::checkInt64($var);
        $this->inbox_id = $var;

        return $this;
    }

    /**
     *邮件生效时间
     *
     * Generated from protobuf field <code>string start_time = 2;</code>
     * @return string
     */
    public function getStartTime()
    {
        return $this->start_time;
    }

    /**
     *邮件生效时间
     *
     * Generated from protobuf field <code>string start_time = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setStartTime($var)
    {
        GPBUtil::checkString($var, True);
        $this->start_time = $var;

        return $this;
    }

    /**
     *邮件失效时间
     *
     * Generated from protobuf field <code>string end_time = 3;</code>
     * @return string
     */
    public function getEndTime()
    {
        return $this->end_time;
    }

    /**
     *邮件失效时间
     *
     * Generated from protobuf field <code>string end_time = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setEndTime($var)
    {
        GPBUtil::checkString($var, True);
        $this->end_time = $var;

        return $this;
    }

    /**
     *邮件所需参数json
     *
     * Generated from protobuf field <code>string params = 4;</code>
     * @return string
     */
    public function getParams()
    {
        return $this->params;
    }

    /**
     *邮件所需参数json
     *
     * Generated from protobuf field <code>string params = 4;</code>
     * @param string $var
     * @return $this
     */
    public function setParams($var)
    {
        GPBUtil::checkString($var, True);
        $this->params = $var;

        return $this;
    }

}

