<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: inbox.proto

namespace Inbox;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>inbox.AddRequest</code>
 */
class AddRequest extends \Google\Protobuf\Internal\Message
{
    /**
     *用户id
     *
     * Generated from protobuf field <code>int64 uid = 1;</code>
     */
    protected $uid = 0;
    /**
     * Generated from protobuf field <code>.inbox.AddInboxData data = 2;</code>
     */
    protected $data = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int|string $uid
     *          用户id
     *     @type \Inbox\AddInboxData $data
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Inbox::initOnce();
        parent::__construct($data);
    }

    /**
     *用户id
     *
     * Generated from protobuf field <code>int64 uid = 1;</code>
     * @return int|string
     */
    public function getUid()
    {
        return $this->uid;
    }

    /**
     *用户id
     *
     * Generated from protobuf field <code>int64 uid = 1;</code>
     * @param int|string $var
     * @return $this
     */
    public function setUid($var)
    {
        GPBUtil::checkInt64($var);
        $this->uid = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.inbox.AddInboxData data = 2;</code>
     * @return \Inbox\AddInboxData|null
     */
    public function getData()
    {
        return $this->data;
    }

    public function hasData()
    {
        return isset($this->data);
    }

    public function clearData()
    {
        unset($this->data);
    }

    /**
     * Generated from protobuf field <code>.inbox.AddInboxData data = 2;</code>
     * @param \Inbox\AddInboxData $var
     * @return $this
     */
    public function setData($var)
    {
        GPBUtil::checkMessage($var, \Inbox\AddInboxData::class);
        $this->data = $var;

        return $this;
    }

}

