<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: inbox.proto

namespace Inbox;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>inbox.InboxContent</code>
 */
class InboxContent extends \Google\Protobuf\Internal\Message
{
    /**
     *邮件自增id
     *
     * Generated from protobuf field <code>int64 id = 1;</code>
     */
    protected $id = 0;
    /**
     *邮件模板id
     *
     * Generated from protobuf field <code>int64 inbox_id = 2;</code>
     */
    protected $inbox_id = 0;
    /**
     *优先级
     *
     * Generated from protobuf field <code>int64 sort = 3;</code>
     */
    protected $sort = 0;
    /**
     *邮件类型
     *
     * Generated from protobuf field <code>string type = 4;</code>
     */
    protected $type = '';
    /**
     *邮件名称
     *
     * Generated from protobuf field <code>string title = 5;</code>
     */
    protected $title = '';
    /**
     *邮件内容
     *
     * Generated from protobuf field <code>string content = 6;</code>
     */
    protected $content = '';
    /**
     *邮件图标
     *
     * Generated from protobuf field <code>string icon = 7;</code>
     */
    protected $icon = '';
    /**
     *邮件奖励礼包
     *
     * Generated from protobuf field <code>int64 gift_id = 8;</code>
     */
    protected $gift_id = 0;
    /**
     *邮件生效时间
     *
     * Generated from protobuf field <code>string start_time = 9;</code>
     */
    protected $start_time = '';
    /**
     *邮件失效时间
     *
     * Generated from protobuf field <code>string end_time = 10;</code>
     */
    protected $end_time = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int|string $id
     *          邮件自增id
     *     @type int|string $inbox_id
     *          邮件模板id
     *     @type int|string $sort
     *          优先级
     *     @type string $type
     *          邮件类型
     *     @type string $title
     *          邮件名称
     *     @type string $content
     *          邮件内容
     *     @type string $icon
     *          邮件图标
     *     @type int|string $gift_id
     *          邮件奖励礼包
     *     @type string $start_time
     *          邮件生效时间
     *     @type string $end_time
     *          邮件失效时间
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Inbox::initOnce();
        parent::__construct($data);
    }

    /**
     *邮件自增id
     *
     * Generated from protobuf field <code>int64 id = 1;</code>
     * @return int|string
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     *邮件自增id
     *
     * Generated from protobuf field <code>int64 id = 1;</code>
     * @param int|string $var
     * @return $this
     */
    public function setId($var)
    {
        GPBUtil::checkInt64($var);
        $this->id = $var;

        return $this;
    }

    /**
     *邮件模板id
     *
     * Generated from protobuf field <code>int64 inbox_id = 2;</code>
     * @return int|string
     */
    public function getInboxId()
    {
        return $this->inbox_id;
    }

    /**
     *邮件模板id
     *
     * Generated from protobuf field <code>int64 inbox_id = 2;</code>
     * @param int|string $var
     * @return $this
     */
    public function setInboxId($var)
    {
        GPBUtil::checkInt64($var);
        $this->inbox_id = $var;

        return $this;
    }

    /**
     *优先级
     *
     * Generated from protobuf field <code>int64 sort = 3;</code>
     * @return int|string
     */
    public function getSort()
    {
        return $this->sort;
    }

    /**
     *优先级
     *
     * Generated from protobuf field <code>int64 sort = 3;</code>
     * @param int|string $var
     * @return $this
     */
    public function setSort($var)
    {
        GPBUtil::checkInt64($var);
        $this->sort = $var;

        return $this;
    }

    /**
     *邮件类型
     *
     * Generated from protobuf field <code>string type = 4;</code>
     * @return string
     */
    public function getType()
    {
        return $this->type;
    }

    /**
     *邮件类型
     *
     * Generated from protobuf field <code>string type = 4;</code>
     * @param string $var
     * @return $this
     */
    public function setType($var)
    {
        GPBUtil::checkString($var, True);
        $this->type = $var;

        return $this;
    }

    /**
     *邮件名称
     *
     * Generated from protobuf field <code>string title = 5;</code>
     * @return string
     */
    public function getTitle()
    {
        return $this->title;
    }

    /**
     *邮件名称
     *
     * Generated from protobuf field <code>string title = 5;</code>
     * @param string $var
     * @return $this
     */
    public function setTitle($var)
    {
        GPBUtil::checkString($var, True);
        $this->title = $var;

        return $this;
    }

    /**
     *邮件内容
     *
     * Generated from protobuf field <code>string content = 6;</code>
     * @return string
     */
    public function getContent()
    {
        return $this->content;
    }

    /**
     *邮件内容
     *
     * Generated from protobuf field <code>string content = 6;</code>
     * @param string $var
     * @return $this
     */
    public function setContent($var)
    {
        GPBUtil::checkString($var, True);
        $this->content = $var;

        return $this;
    }

    /**
     *邮件图标
     *
     * Generated from protobuf field <code>string icon = 7;</code>
     * @return string
     */
    public function getIcon()
    {
        return $this->icon;
    }

    /**
     *邮件图标
     *
     * Generated from protobuf field <code>string icon = 7;</code>
     * @param string $var
     * @return $this
     */
    public function setIcon($var)
    {
        GPBUtil::checkString($var, True);
        $this->icon = $var;

        return $this;
    }

    /**
     *邮件奖励礼包
     *
     * Generated from protobuf field <code>int64 gift_id = 8;</code>
     * @return int|string
     */
    public function getGiftId()
    {
        return $this->gift_id;
    }

    /**
     *邮件奖励礼包
     *
     * Generated from protobuf field <code>int64 gift_id = 8;</code>
     * @param int|string $var
     * @return $this
     */
    public function setGiftId($var)
    {
        GPBUtil::checkInt64($var);
        $this->gift_id = $var;

        return $this;
    }

    /**
     *邮件生效时间
     *
     * Generated from protobuf field <code>string start_time = 9;</code>
     * @return string
     */
    public function getStartTime()
    {
        return $this->start_time;
    }

    /**
     *邮件生效时间
     *
     * Generated from protobuf field <code>string start_time = 9;</code>
     * @param string $var
     * @return $this
     */
    public function setStartTime($var)
    {
        GPBUtil::checkString($var, True);
        $this->start_time = $var;

        return $this;
    }

    /**
     *邮件失效时间
     *
     * Generated from protobuf field <code>string end_time = 10;</code>
     * @return string
     */
    public function getEndTime()
    {
        return $this->end_time;
    }

    /**
     *邮件失效时间
     *
     * Generated from protobuf field <code>string end_time = 10;</code>
     * @param string $var
     * @return $this
     */
    public function setEndTime($var)
    {
        GPBUtil::checkString($var, True);
        $this->end_time = $var;

        return $this;
    }

}

