<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: inbox.proto

namespace Inbox;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>inbox.OperateRequest</code>
 */
class OperateRequest extends \Google\Protobuf\Internal\Message
{
    /**
     *邮件id
     *
     * Generated from protobuf field <code>int64 id = 1;</code>
     */
    protected $id = 0;
    /**
     *操作类型
     *
     * Generated from protobuf field <code>int64 type = 2;</code>
     */
    protected $type = 0;
    /**
     *用户id
     *
     * Generated from protobuf field <code>int64 uid = 3;</code>
     */
    protected $uid = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int|string $id
     *          邮件id
     *     @type int|string $type
     *          操作类型
     *     @type int|string $uid
     *          用户id
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Inbox::initOnce();
        parent::__construct($data);
    }

    /**
     *邮件id
     *
     * Generated from protobuf field <code>int64 id = 1;</code>
     * @return int|string
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     *邮件id
     *
     * Generated from protobuf field <code>int64 id = 1;</code>
     * @param int|string $var
     * @return $this
     */
    public function setId($var)
    {
        GPBUtil::checkInt64($var);
        $this->id = $var;

        return $this;
    }

    /**
     *操作类型
     *
     * Generated from protobuf field <code>int64 type = 2;</code>
     * @return int|string
     */
    public function getType()
    {
        return $this->type;
    }

    /**
     *操作类型
     *
     * Generated from protobuf field <code>int64 type = 2;</code>
     * @param int|string $var
     * @return $this
     */
    public function setType($var)
    {
        GPBUtil::checkInt64($var);
        $this->type = $var;

        return $this;
    }

    /**
     *用户id
     *
     * Generated from protobuf field <code>int64 uid = 3;</code>
     * @return int|string
     */
    public function getUid()
    {
        return $this->uid;
    }

    /**
     *用户id
     *
     * Generated from protobuf field <code>int64 uid = 3;</code>
     * @param int|string $var
     * @return $this
     */
    public function setUid($var)
    {
        GPBUtil::checkInt64($var);
        $this->uid = $var;

        return $this;
    }

}

