<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: php/inbox.proto

namespace Inbox;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>inbox.ListResponse</code>
 */
class ListResponse extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>repeated .inbox.InboxContent list = 1;</code>
     */
    private $list;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Inbox\InboxContent[]|\Google\Protobuf\Internal\RepeatedField $list
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Php\Inbox::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>repeated .inbox.InboxContent list = 1;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getList()
    {
        return $this->list;
    }

    /**
     * Generated from protobuf field <code>repeated .inbox.InboxContent list = 1;</code>
     * @param \Inbox\InboxContent[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setList($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Inbox\InboxContent::class);
        $this->list = $arr;

        return $this;
    }

}

