<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: php/inbox.proto

namespace Inbox;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>inbox.UIdRequest</code>
 */
class UIdRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>int64 uid = 1;</code>
     */
    protected $uid = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int|string $uid
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Php\Inbox::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>int64 uid = 1;</code>
     * @return int|string
     */
    public function getUid()
    {
        return $this->uid;
    }

    /**
     * Generated from protobuf field <code>int64 uid = 1;</code>
     * @param int|string $var
     * @return $this
     */
    public function setUid($var)
    {
        GPBUtil::checkInt64($var);
        $this->uid = $var;

        return $this;
    }

}

